AllCops:
  Exclude:
    - test/dummy/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Exclude:
    - titleist.gemspec
    - test/test_helper.rb
    - bin/rails

Style/FormatStringToken:
  Exclude:
    - lib/titleist/title.rb
