name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby_version: 2.6.x
      - run: sudo apt-get install -yy libsqlite3-dev
      - run: bundle install
      - run: bundle exec rake
